name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - { os: ubuntu-latest, workflow: build-linux, qt-arch: linux_gcc_64 }
          - { os: windows-latest, workflow: build-windows, qt-arch: win64_msvc2019_64 }
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: "1.3.283.0"
          vulkan-components: Vulkan-Headers
          vulkan-use-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.1'
          arch: ${{ matrix.platform.qt-arch }}
          dir: lib/qt
          setup-python: false
          cache: true
          modules: qtmultimedia qtwebsockets

      - name: Install required packages
        if: startsWith(matrix.platform.os, 'ubuntu')
        run: |
          sudo apt-get install -y libxtst-dev clang-tidy


      - uses: lukka/run-cmake@v10
        with:
          workflowPreset: ${{ matrix.platform.workflow }}
        env:
          CMAKE_CXX_CLANG_TIDY: clang-tidy

